### ISSUE TITLE
Valores de metadatos elegibles y persistentes

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#1]
Los valores de algunos campos de los metadatos deben poder elegirse de un widget combobox o similar y se debe permitir agregar o quitar valor a la lista de los valores posibles. Estos valores deben persistir entre sesiones. Además, se debe poder elegir un default.

@Nehuen por favor lista acá los campos a aplicarle este widget.

**Comment by nehuenpereyra** [comment]
En un principio, sería requerido para estos tres metadatos:
- OBSERVER
- DIGITALI
- IMAGETYP

**Comment by facundoq** [comment]
@joaquinmir este también

**Comment by joaquinmir** [comment]
https://www.youtube.com/watch?v=ukpSOD2xbmU

**Comment by facundoq** [comment]
Genial Joaquín!
Respecto a los dos modos de guardar, digamosles precargar valores vs recordar valores, se aplicarian a distintos campos pero ambas formas están bien.
En los campos OBSERVAT, SCANNER, SCAN-RES, SCAN-COL, SOFTWARE y DETECTOR, los valores deberían siempre precargarse, sin poder agregar nuevos desde la interfaz principal. 

Los tres campos de arriba 

OBSERVER
DIGITALI
IMAGETYP

Según Yael podrían también escribirse nuevos y que se guarden pero no sé... Si fuera así debería quedar más claro desde la ui que estás agregando un valor nuevo y que se va a guardar. Me parece más lío. Yo dejaría todo como precargar por ahora en esos campos.

Respecto a guardar los datos en local storage, lo tendríamos que ver pq quizás sería mejor que queden en el servidor, pero por ahora está joya.

**Comment by joaquinmir** [comment]
> Según Yael podrían también escribirse nuevos y que se guarden pero no sé... Si fuera así debería quedar más claro desde la ui que estás agregando un valor nuevo y que se va a guardar. Me parece más lío. Yo dejaría todo como precargar por ahora en esos campos.

Dale eso se cambia facil, y lo del metodo de guardado elegi ese porque es poca informacion y ademas esta relacionada con la configuracion, pero si hace falta guardarlo en el servidor lo hacemos, de ultima cuando ya haya terminado lo otro.

**Comment by facundoq** [comment]
Quitar el botón "Seleccionar" al cambiar el valor por defecto
