### ISSUE TITLE
Label de estado que indique que todo esté guardado

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#19]
Básicamente un visualizador del flag de hubo cambios/ fueron guardados

**Comment by joaquinmir** [comment]
![ezgif-4-9f9653cd23](https://user-images.githubusercontent.com/97806069/168893740-e6ee0b55-6cd9-4bc0-b6f3-74cec82c076d.gif)

Estuve viendo y se me ocurrio ese como el mejor lugar para colocar el icono, se ve siempre y esta relacionado con el archivo. Si esta guardado esta el tick y si no te avisa que se esta guardando con la animacion esa.

**Comment by facundoq** [comment]
Me gusta! Veamos el viernes que dicen!
