### ISSUE TITLE
Nombres de los archivos fits generados

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#2]
Los nombres de lo archivos fits a generar deberían componerse tanto del nombre del archivo original como del object ID del espectro dentro de archivo. Algo asi como ARCHIVOORIGINAL_OBJECTID.fits . De esa manera, además, si se vuelve a procesar un archivo original se puede saber si ya tiene espectros generados a partir del mismo. 

En el fits, además entonces, debería guardarse el bounding box con el que se recortó el espectro en el archivo original.

Además, en la UI debería indicarse cuando un espectro ya ha sido guardado en disco con una tilde verde, y cuando no con un signo de exclamación amarillo o rojo. Al modificarse luego de guardado, debe nuevamente ponerse el signo de exclamación

Alternativa: SIEMPRE persistir los espectros, ante cualquier cambio, tipo como funciona google docs.

**Comment by joaquinmir** [comment]
> Además, en la UI debería indicarse cuando un espectro ya ha sido guardado en disco con una tilde verde, y cuando no con un signo de exclamación amarillo o rojo. Al modificarse luego de guardado, debe nuevamente ponerse el signo de exclamación

¿Osea que si cargo una imagen nueva tiene el programa que poder detectar que ya fue procesada anteriormente? O te referis a que cuando cargo una imagen nueva deberia aparecer un icono amarillo que se pone en verde luego de que la guardo (es decir que toda la logica se mantenga solo en la sesión)

**Comment by facundoq** [comment]
No, con espectro me refiero a un espectro dentro de la imagen. Si volvés a abrir una imagen con espectros ya procesados, debería indicar que han sido procesados. 

Caso de uso: 
Persona carga una imagen, anota dos de los tres espectros, termina su día de trabajo. Vuelve al día siguiente, abre la imagen, y debe saber qué espectros ya etiquetó y cuales no rápidamente.

**Comment by facundoq** [comment]
Repensando esto, creo que sería mejor que sea tipo google docs, sin un botón de guardar, que los cambios se guarden automáticamente cada x segundos.

**Comment by joaquinmir** [comment]
@facundoq Para el autoguardado vos decis de hacerlos cada x segundos ? tambien se me ocurria usar la funcion onchange que tienen los campos , pero se ejecutaria cada vez que se escribe/borra un caracter y capaz que se va a complicar con el procesamiento que lleva hacer todo el guardado. Otra seria cada x segundos y ademas cada vez que se hace alguna accion como salir de la ventana de "Mas metadatos" o de borrar un bbox.

**Comment by facundoq** [comment]
Joaco, para las ediciones yo lo pensaría registrando el `onchange` de modo que ponga en true un flag global de "changed" del espectro. Después tenés como decís un timer que cada 5 segundos se fija si hubo cambios y si es así los persiste, pero no hacerlo en cada `onchange` porque va a ser imposible.

Obvio que como vos decís cuando se borra un bbox quizás hay que hacerlo de forma inmediata, pero como decíamos eso debería ir con confirmación (si es que tiene metadatos guardados). Hago un issue con eso aparte si te parece.

**Comment by joaquinmir** [comment]
Capaz directamente estaria bueno hacer un issue con el titulo "Autoguardado" o algo asi que englobe todo menos el tema del nombre de los fits.

**Comment by facundoq** [comment]
Adelante, armenlo!
