### ISSUE TITLE
ReDiseño de la interfaz

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#20]
![IMG_20220513_105004846](https://user-images.githubusercontent.com/1576711/168298149-a7994143-6bb1-4e15-841d-964239524945.jpg)

**Comment by joaquinmir** [comment]
![image](https://user-images.githubusercontent.com/97806069/168444410-7193c456-168e-4a1c-843c-c35cb5a133d3.png)
Algo asi estaria bien? Incluso lo podemos hacer andar para la demo con los de astronomia. Despues se puede dejar mas lindo

**Comment by facundoq** [comment]
Me gusta! Algunos comentarios:

* El botón de buscar Espectros lo sacaría: al cargar una imagen, si no
tiene Espectros se hace la detección, si tiene no se la hace y se cargan
del json, y punto.
* al botón de valores por defecto le agregaría un icono de engranaje para
este se entienda y lo pondria donde está el botón de buscar metadatos
* Al botón de buscar metadatos lo pondria con los inputs de texto
* Guardar fits creo que sería mejor que se llame exportar fits para dejar
claro que lo que se está haciendo no genera un fits automáticamente

**Comment by joaquinmir** [comment]
@facundoq Se me ocurre que deberia haber algun boton para limpiar todo, es decir que borre todos los espectros.

**Comment by facundoq** [comment]
Podría ser pero cuál sería el caso de uso?

Que se detecten muy mal todos los Espectros? Y la cantidad?

**Comment by joaquinmir** [comment]
Mas que nada porque el borrado es medio engorroso, ya borrar 3 espectros se hace pesado. Sino capaz que haya un boton afuera del canvas para borrar un espectro determinado, al lado de exportar fits o en algun lado

**Comment by facundoq** [comment]
Me parece que va más esa, cuanto mucho son varios clicks y listo. Entiendo
igual que para el testeo es medio pachorra :)
