### ISSUE TITLE
Atributos de la placa

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#22]
Los campos para atributos de la placa deberían ser los mismos para toda la placa y modificarse desde un solo lugar independiente a los espectros

Los campos son:

* Digitalizador
* Nro placa (obligatorio para exportar)
* observatorio,
* scanner
* scan res
* scan col
* telescopio
* instrumento

**Comment by joaquinmir** [comment]
Facu, el observatorio seguro que es global? o te confundiste con observador?

**Comment by facundoq** [comment]
Lo mismo no? Si es la misma placa...

**Comment by joaquinmir** [comment]
Okey entonces observador y observatorio las dos globales.

**Comment by facundoq** [comment]
Le consultamos a Roberto y Yael!

**Comment by facundoq** [comment]
Joaco, observatorio seguro es global porque es muy raro que muevan la placa de un lugar a otro. 
Pensandolo, observador *podría* ser distinto si dos personas compartían la placa, pero por ahora dejemoslo también global y si sale el caso vemos como se da. Quizás es el 0.00001% de los casos y no le damos bola.

**Comment by facundoq** [comment]
Acá faltaría "Telescopio" (TELESCOP) e "Instrumento" (INSTRUME), 
https://docs.google.com/spreadsheets/d/1CHNl8fuzF1MvuetgiIIUFCZG6jOUW73b/edit#gid=609270399

**Comment by Sansanto2000** [comment]
Esto ya esta resuelto, cierro issue
