### ISSUE TITLE
Generar txt con texto para subir al sedici

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#29]
Que se genere en una carpeta aparte llamada "sedici_txt", con un archivo por cada espectro con la descripción del mismo.

**Comment by joaquinmir** [comment]
Para esto necesito bien el formato del contenido del texto, que creo que yael lo tenia.

**Comment by facundoq** [comment]
Les escribimos!

**Comment by facundoq** [comment]
Buenas, revisando veo que el output esperado es, por ejemplo
<http://sedici.unlp.edu.ar/handle/10915/84209>:

Archivo en formato FITS de la placa espectrográfica identificada como A4408
de la fuente astronómica AG Car observada el 24 de febrero de 1976 desde
CTIO: Cerro Tololo Interamerican Observatory. Digitalizado con un escaner
Nikon LS-9000ED en el marco del proyecto de "Recuperación del Trabajo
Observacional Histórico (ReTrOH)" de la Facultad de Ciencias Astronómicas y
Geofísicas de la Universidad Nacional de La Plata (FCAG-UNLP) en
colaboración con Nuevo Observatorio Virtual Argentino (NOVA).

O sea que el formato sería:
"Archivo en formato FITS de la placa espectrográfica identificada como
{id_placa} de la fuente astronómica {*id_objeto*} observada {
*fecha_observacion*} desde {*observatorio*}. Digitalizado con un escaner
Nikon LS-9000ED en el marco del proyecto de "Recuperación del Trabajo
Observacional Histórico (ReTrOH)" de la Facultad de Ciencias Astronómicas y
Geofísicas de la Universidad Nacional de La Plata (FCAG-UNLP) en
colaboración con Nuevo Observatorio Virtual Argentino (NOVA)."


Adjunté la parte relevante del código que generaba estos txts pero seguro
la pueden simplificar ustedes. En particular, el código lidia con casos en
donde no está la información relevante, por ejemplo, si no está la fecha
dice "observada *en fecha desconocida*".

Saludos!

**Comment by facundoq** [comment]
````python
 # Genero un archivo txt con info para subir al SEDICI

        print("\n GENERO ARCHIVO TXT \n")

        archivo= imagen[:imagen.find('.')] + '_SEDICI.txt'
        file= open(archivo, 'w') # Abro el archivo de escritura

        i= list(campos).index('PLATE-N')
        plate_n= val[i]

        i= list(campos).index('OBJECT')
        obj= val[i]

        if plate_n != '':
            titulo= 'Placa espectrográfica identificada como ' + plate_n
        else:
            titulo= 'Placa espectrográfica sin identificación'
        if obj != '':
            titulo= titulo + ' de la fuente astronómica ' + obj
        else:
            titulo= titulo + ' de una fuente astronómica desconocida'
            
        file.write( 'TITULO: ' + titulo + '\n\n')

        i= list(campos).index('DATE-OBS')
        dateobs= val[i]

        resumen= 'Archivo en formato FITS de la p' + titulo[1:]
        
        if dateobs != '':
            fecha= dateobs.split('-')
            year= int(fecha[0])
            dia= int(fecha[2])
            mes= busco_mes(fecha[1])
            fecha= "{0:0>2d} de {1} de {2}".format(dia, mes, year)
            resumen= resumen + ' observada el ' + fecha
        else:
            fecha= 'desconocida'
            resumen= resumen + ' observada en fecha ' + fecha
            
        file.write( "FECHA DE PUBLICACION: " + fecha + '\n\n')

        resumen= resumen + ' desde '

        i= list(campos).index('OBSERVAT')
        observat= val[i]
        
        s= -1
        l= len(observatorios) -1
        j= 0
        while s == -1 and j <= l:
            try:
                s= observatorios[j].index(observat+ ':')
                k= len(observat)
                observat= observat.upper() + observatorios[j][k:]
            except:
                j= j+1
                
        if s != -1 and j > 0 and j < l:
            resumen= resumen + observat + '. '
        else:
            resumen= resumen + 'observatorio desconocido. '

        resumen= resumen + 'Digitalizado con un escaner Nikon LS-9000ED en el marco del proyecto de "Recuperación del Trabajo Observacional Histórico (ReTrOH)" de la Facultad de Ciencias Astronómicas y Geofísicas de la Universidad Nacional de La Plata (FCAG-UNLP) en colaboración con Nuevo Observatorio Virtual Argentino (NOVA).'
        file.write( 'RESUMEN: ' + resumen)
        file.close()

````

**Comment by joaquinmir** [comment]
El tema es que los datos que chequea el script ese son todos los obligatorios, osea que nunca faltarian. Lo hago igual como dice ahi o asumo que van a llegar siempre todos los datos?

**Comment by facundoq** [comment]
Es cierto, pero no está de más considerar ese caso por si mañana cambiamos
los requisitos de obligatoriedad!
