### ISSUE TITLE
Cambiar checkbox de ver finalizados por un combo

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#35]

**Comment by joaquinmir** [comment]
Este me acuerdo que habiamos acordado otra cosa despues charlandolo, como seria al final ? O se dejaba como esta?

**Comment by facundoq** [comment]
No, habíamos quedado en que sea un combo y que quede la funcionalidad igual (o muestra los terminados o los "en proceso" pero no ambos la mismo tiempo).
