### ISSUE TITLE
Guardar la transformación Seleccionada para cada imagen

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#38]
Si el usuario cambia la transformación, que se persista para la próxima vez que abra la app o si abre  otra imagen y vuelve. Persistirlo junto con los bounding boxes

**Comment by Sansanto2000** [comment]
Considerando la dinámica de uso de los filtros contemplada por el issue https://github.com/midusi/spectrogram/issues/59 ¿este sigue siendo necesario?

**Comment by facundoq** [comment]
No entiendo a qué te referis con cache ¿Del navegador?

**Comment by Sansanto2000** [comment]
Si, capaz no es la mejor palabra, pero actualmente, cuando uno presiona el botón `💾` para guardar la configuración de los filtros, los valores importantes se guardan en `localstorage` (una facilidad de los navegadores para el almacenamiento de ciertos valores del lado del usuario), de forma tal que al seleccionar otra imagen, los filtros se setean según lo guardado en `localstorage`. 
> 
Entiendo que este Issue lo que estaría indicando es que las transformaciones también se persistan por imagen guardada en el servidor, ósea que los filtros se configuren según la disponibilidad de valores, 1ro en el servidor, la información que guarda de cada imagen a medio procesar, 2do en `localstorage`, lo que el propio usuario configuro, y 3ro, si no hay nada configurado y la imagen nunca fue abierta entonces se usan los valores por defecto.
> 
Del lado del usuario, me parece un poco contra intuitivo que algunas imágenes guarden su configuración individual cuando acceda a ellas y otras permanezcan según lo que el especifico con `💾`. Ya que el capaz no se ponga a pensar en que el software reserva usa una configuración de filtros para imágenes a medio procesar que para otras nuevas, desde su perspectiva probablemente lo que piense es que el botón `💾` funciona mal.
> 
De cualquier forma, solo pregunto para estar seguro de que hay que hacer, ustedes digan y hago los ajustes que correspondan.
