### ISSUE TITLE
Controles para seleccionar placa y Espectros

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#39]
Primero va la placa (que diga Placa) luego un label " Espectros:" y luego los Espectros (1,2,etc)

**Comment by joaquinmir** [comment]
Algo asi? : 

![image](https://user-images.githubusercontent.com/97806069/174034193-b73962cc-93b4-44b1-9fad-403d4f671a00.png)

**Comment by joaquinmir** [comment]
![image](https://user-images.githubusercontent.com/97806069/174943411-0b629089-10d2-47ba-9271-1125dc58eec2.png)

**Comment by joaquinmir** [comment]
A mi me gusta como se resaltan los seleccionados, de ultima podria ser que el borde se haga mas grande, lo del color creo que no se veria bien.
