### ISSUE TITLE
Manejar falta de conexión en búsqueda de metadatos

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#42]
Si no hay conexión, permitir cargar a mano
Mostrar mensaje flotante que desaparece a los 5 segundos indicando la falla de conexión.

Lo mismo debe pasar si hay conexión pero no sé encuentra el objeto

**Comment by joaquinmir** [comment]
Aca tengo una duda, porque la idea es que no se pueda laburar sin conexion al servidor. Entonces solo deberia dejar cargar a mano si se da otro error como por ejemplo que no se encuentre el objeto?

**Comment by facundoq** [comment]
Joaco, hay 2 servidores: el de la app, y el de los metadatos (externos).
Acá hablamos del server de los metadatos. Obvio que si no hay conexión al
server de la app no se puede.
