### ISSUE TITLE
No permitir cargar la aplicación sin conexión al servidor

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#48]
Al iniciar la aplicación, si el servidor no está funcionando se muestra un modal diciendo que hubo un error en el server.

![Screenshot_20220610_184331](https://user-images.githubusercontent.com/1576711/173155480-d6a906ef-b127-4817-8106-799ea59a3332.png)

En lugar de eso, indicar que "No se pudo conectar con el servidor; recargue la página para volver a intentarlo", y no dejar que se cierre el mensaje modal.

No sé como lo están haciendo por atrás, pero otra opción seŕia que el frontend podría quedar haciendo polling al server hasta que pueda conectarse, y recién ahí se quite el mensaje modal. Eso podría funcionar para todos los requests, es decir, podría ser una funcionalidad genérica de que si un request no funciona porque el servidor está abajo, se impide usar la app hasta que se restaure la conexión, y se reintente hacer la operación mientras.

En cualquier caso, podrían utilizar un [ícono](https://www.flaticon.com/premium-icon/cloud-computing_3756620?term=server%20offline&page=1&position=1&page=1&position=1&related_id=3756620&origin=style) más adecuado también para indicar la falta de conexión.

**Comment by joaquinmir** [comment]
![image](https://user-images.githubusercontent.com/97806069/174904194-8d648f0c-de37-4a0d-b7fb-43f374bb48fa.png)
