### ISSUE TITLE
Al ver una placa nueva, por defecto mostrar campos de la placa y no el primer espectro.

### ISSUE THREAD

**Issue by Sansanto2000** [midusi/spectrogram#63]

**Comment by Sansanto2000** [comment]
En general funciona, siempre aparece la info de la placa, pero a veces aparecen seleccionadas la placa y una bbox, saque captura:

![image](https://user-images.githubusercontent.com/64858429/178825739-737622b2-0969-459c-b098-ab36a98ea998.png)

Lo raro es que solo me pasa con 1 .tiff concreto o varias
Lo dejo reportado como bug, veo que puede hacer, pero tampoco termino de entender como es que funciona la selección inicial de tabs, por lo que no se si podre solucionarlo para el viernes.

**Comment by facundoq** [comment]
Quizás sea que al crear un nuevo espectro se le asigna el foco a alguno de
sus campos?
