### ISSUE TITLE
Reentrenar el modelo para detectar espectros con una nueva versión de YOLO (5.0)

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#65]
En la nueva versión está arreglado el bug del Upsample (ver README.md). 

Ver proyecto:
https://github.com/ultralytics/yolov5

También estaría bueno poder separar el código del detector a una nueva carpeta (llamada "detector"), cosa que su entrenamiento sea independiente de uso, y que el backend solo cargue el modelo entrenado.

**Comment by Sansanto2000** [comment]
Estuve mirando este issue y por lo que noto el backend, cuando hace predicciones (en la api de `predict.py`) ya esta cargando el modelo entrenado, solo que este no se guarda en una carpeta llamada `detector`, sino que esta en `backend/app/static/models/`.  Supongo que se podría modularizar un poco mas haciendo una clase python que separe la interacción con el model, pero no se si esto es realmente necesario, ya que el model se llama únicamente en la api predict.

Por otro lado lo de actualizar la versión de YOLO supongo que se puede hacer sin problema.

**Comment by facundoq** [comment]
Genial, si estaría bueno ordenarlo mejor y separar los proyectos porque
YOLO agrega un montón de porquería ahora en el backend!

**Comment by Sansanto2000** [comment]
@facundoq , ahí estuve actualizando la versión del Yolov5, lo que efectivamente soluciono el bug de upsampling.py.

Pero hizo aparecer otro tema. el problema esta relacionado al guardo de las imágenes en la carpeta ".train", en general el primer guardado siempre funciona, pero a partir del segundo siempre tira el siguiente error:
![image](https://user-images.githubusercontent.com/64858429/184503747-9e23001c-bdc7-4240-8642-7d3d727f64b7.png)
Esto definitivamente no ocurría antes, por lo que me dejo un poco desconcertado, pero haciendo unas pruebas logre solucionarlo, 
El tema es que esto implica remplazar la linea `cv2.imwrite(filename, img, [int(cv2.IMWRITE_JPEG_QUALITY), 50])` de backend/app/api/image.py (linea 28) por `cv2.imwrite(filename, img)`. Notar que se estaría borrando el tercer parámetro [int(cv2.IMWRITE_JPEG_QUALITY), 50], el cual lo que hace es reducir la calidad de la imagen a guardar en .train al 50%, esta parte del código no la escribí yo, pero imagino que se hizo así para que no pesen tanto las imágenes de entrenamiento.

Aquí separe 2 capturas del peso de la misma imagen de train guardada con y sin la reducción del 50%:

(Con reducción)
![image](https://user-images.githubusercontent.com/64858429/184504069-1e7cd0b3-fce7-4c52-bdab-ca123deebde2.png)


(Sin reducción)
![image](https://user-images.githubusercontent.com/64858429/184504025-154379bb-1e91-42fc-8351-de80c438ceb5.png)

No encuentro una solución evidente que mantenga la reducción y que solucione el error que provoca que solo se procese la primera imagen, por lo que quiero preguntar si es importante mantener esta reducción de peso, o si puedo descartarla, solucionando el bug en el proceso.
Si no se puede descartar entonces seguiré buscando en busca de alternativas.

**Comment by facundoq** [comment]
Está perfecto así, de hecho es mejor, no tiene sentido reducir la calidad!

**Comment by Sansanto2000** [comment]
Okey, entonces me gustaría preguntar otra cosa; ¿Hay alguna razón para guardarlos como .jpg? Por que por lo que veo el cv2.imread soporta guardado de ".tiff"; Ademas el guardado de .jpg por defecto lo guarda con un 95% de calidad, y siendo que no puedo especificar [int(cv2.IMWRITE_JPEG_QUALITY), 100] no habría forma de modificar esta reducción implícita en el formato

**Comment by facundoq** [comment]
Por mí guardemos en png que tiene compresión, el uso de tiff es por el
escaneado pero es un formato medio feo

**Comment by Sansanto2000** [comment]
Ok, hago los cambios pertinentes para que se guarde en "png".

PD: Mientras hacia esto me encontré con un bug fatal en la versión de development que impedía la exportación de los fits resultantes, causado por la versión de la librería astropy. Ya lo corregí actualizando los métodos usados con los nuevos parámetros, y actualice requirements.txt para fije la versión.

**Comment by Sansanto2000** [comment]
Listo, ahí subí los cambios necesarios para el cambio de formato en el guardado en el branch "65-reentrenar-modelo", subo captura de cual es el peso del .tiff de las capturas anteriores, para que se pueda apreciar la diferencia que implica guardarlo en png:
![image](https://user-images.githubusercontent.com/64858429/184562962-41a2fbfc-eb1c-4502-b763-62a3206ce4e1.png)
Sin duda pesa mas, cerca de 4 veces el jpg al 95%, pero creo que sigue siendo un tamaño manejable.

**Comment by Sansanto2000** [comment]
Con esto el Issue casi esta listo, falta la parte de reentrenar el modelo, si hay algún conjunto de imágenes que me puedan facilitar para entrenar el modelo genial, sino veo que puedo hacer en base a imagenes online

**Comment by facundoq** [comment]
@Nehuen Pereyra ***@***.***> había generado esas imágenes, nos
podrías decir donde?

**Comment by nehuenpereyra** [comment]
Si, @facundoq ya le compartí la carpeta y el archivo comprimido se llama dataset_361.zip

**Comment by Sansanto2000** [comment]
No estaba en el Issue inicial, pero aprovechando que habia movido todo lo relacionado a yolov5 a la carpeta detector. Implemente una vercion breve del patron singleton para la carga del modelo que se usa para las predicciones.
Para el que lo use el cambio es invisible, pero ahora el modelo de prediccion solo se carga una vez y no cada que se quieren predecir los espectros de un nuevo tiff. Con esto, por lo menos en local, note una mejora notable en los tiempos de respuesta de las predicciones.
Solo eso, lo comento aca para que quede registro, y, si, por si acaso creen que el uso de un singleton en este caso es contraproducente puedan decirmelo.
Tema aparte; con esto ya casi esta el issue, todavia quiero refinar algunos detalles, pero probablemente mañana a la tarde ya este mergeando los cambios a development

**Comment by facundoq** [comment]
Buenísimo Santi!
