### ISSUE TITLE
Confirmar borrado de espectros con metadatos

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#7]
Cuando se cargan datos de un espectro (al menos 1 campo), y luego se quiere borrar el espectro, se debe pedir confirmación al usuario e indicarle que va a perder los metadatos de _ese_ espectro de forma irreversible.

**Comment by joaquinmir** [comment]
Si lo pregunta siempre seria un problema? Digo tampoco es que lo va a hacer muy seguido el usuario

**Comment by facundoq** [comment]
No, no sería un problema porque como decís no debería borrar espectros con datos muy seguido. Si va a ser normal que borre espectros sin datos, eso es entendible porque al principio está alineando los bounding boxes.

**Comment by facundoq** [comment]
La otra opción sería hacerlo en etapas: en una etapa selecciona los bboxes, y luego en la siguiente etapa edita los campos de los mismos. Si quiere borrarlos tiene que volver a la etapa anterior. Eso nos facilita el tema de que una vez que los selecciona y pasa a la 2da etapa ya sabés que no hay que borrar, es solo editar los campos de un fits que existe.

**Comment by joaquinmir** [comment]
Yo tambien lo decia porque ya el hecho de tener un espectro hace que tengas un dato en la base de datos, que seria el bbox.

**Comment by facundoq** [comment]
Tal cual si, eso viene en conjunto, si borras un bbox implica que _no había_ un espectro en ese área así que serían lo mismo no?

**Comment by joaquinmir** [comment]
> Tal cual si, eso viene en conjunto, si borras un bbox implica que _no había_ un espectro en ese área así que serían lo mismo no?

O si habia y lo queres borrar por x razon, a lo que voy es que consultar siempre antes de borrar tiene sentido porque siempre que borres se van a perder datos.

**Comment by facundoq** [comment]
Dale, para mi en el caso en que el espectro sea el detectado por el algoritmo inicial y no haya sido modificado ni tenga ningún valor se podría borrar sin confirmación, pero por ahora pongamos confirmacioń siempre y si lo vemos engorroso lo agregamos!

**Comment by facundoq** [comment]
¿Qué está sucediendo ahora si se cargan algunos datos de los espectors, y se vuelve a correr el detector de bounding boxes?

**Comment by joaquinmir** [comment]
> ¿Qué está sucediendo ahora si se cargan algunos datos de los espectors, y se vuelve a correr el detector de bounding boxes?

Se resetea todo, pensaba tambien consultar antes de hacerlo. ¿Como deberia funcionar?

**Comment by facundoq** [comment]
Y, por lo mismo creo que debería recalcular todo por detrás, pero solo
agregar aquellos bounding boxes que tienen un IoU menor a 90% con respecto
a los actuales, (y no quitar ninguno!)
