### ISSUE TITLE
Opcion alternativa para campos obligatorios

### ISSUE THREAD

**Issue by Sansanto2000** [midusi/spectrogram#76]
En las pacas que se estan escaneando no se tiene información sobre el osbervatorio, es decir, el campo OBSERVAT de la placa. 
Pusieron como dato ficticio "casleo", pero al buscar los metadatos tira error. 
Dice que el observatorio no está en la base de datos. 
Además, sería bueno que dejara elegir la opción "otro" y no tire error. O que haya una opción en el menú que sea "Sin datos" o algo así.  Podría pensarse algo parecido para todos los metadatos que están como obligatorios.

-> Hacer que haya una opcion otro, o similar, para la mayoria de campos que actualmente estan dispuestos como obligatorios.

**Comment by Sansanto2000** [comment]
Ahi mire el branch development y OBSERVAT es una lista, por lo que no se como hicieron para poner casleo como un dato ficticio, nisiquiera es una opcion. Ademas en la lista ya esta contemplada la opcion "otro", pero esta al final de todo por lo que puede que simplemente no la hubiesen visto.

Aunque si se mantiene el hecho de que si el observatorio es "otro" entonces no permite buscar los metadatos de cada espectro, mostrando un error "El observatorio no esta en la base de datos". Voy a ver que se puede hacer pero si el campo observatorio es requisito para consultar los metadatos entonces no se va a poder hacer mucho.

Respecto a la posibilidad de que los demas campos que estan como obligatorio se vuelvan opcionales tendre que ir viendolos individualmente, pienso que la solucion mas sencilla seria incorporar un valor "-" o similar con el que si se llena con eso entocnes el software sobreentienda que no se tiene ese dato. Podria ser tambien el valor vacio, pero prefiero no usarlo ya que eso podria ser que simplemente se olvido del campo, no que no lo tiene.

**Comment by facundoq** [comment]
Dale, podemos agregar un valor especial MISSING que indique eso no?

**Comment by Sansanto2000** [comment]
Issue solucionado en el ultimo commit, ahora se contempla el input "MISSING" para indicar que no se tiene un campo obligatorio determinado. Marco el Issue como completado.

**Comment by Sansanto2000** [comment]
Reiniciar campos viejos
