### ISSUE TITLE
Modificar doble seleccion para elegir valor por defecto

### ISSUE THREAD

**Issue by Sansanto2000** [midusi/spectrogram#78]
Al momento de elegir un valor por defecto para un determinado campo, de la lista dee valores por defecto que previamente fueron agregados, es flujo es tal que asi:

1. abrir la lista.
2. seleccionar un elemento.
3. Precionar el boton "Seleccionar".

Me parece innecesario el boton seleccionar, ya deberia estar bien con solo seleccionar un elemento, ademas de que es facilmente olvidable, uno selecciona un elemento sale sin precionar el boton, el elemento no se guarda. En un buen caso el usuario se da cuenta y vuelve a entrar, pero es probable que algun usuario no se de cuenta y simplemente piense que la funcionalidad no sirve. 

Por ende me parece correcto directamente modificar el software para que el elemento se seleccione directamente cuando se cliquea el elemento deseado en el paso 2 y asi nos ahorramos el click extra del paso 3.

**Comment by facundoq** [comment]
De acuerdo Santi, dale para adelante!
