### ISSUE TITLE
Al buscar metadatos de un objeto, borrar los valores anteriores de los campos que se buscan

### ISSUE THREAD

**Issue by facundoq** [midusi/spectrogram#82]
Especialmente importante porque para algunos objetos no se traen todos los datos, entonces si en una primera búsqueda se traen todos los datos pero en una segunda no, se mezclarían los datos de objetos distintos.

**Comment by Sansanto2000** [comment]
Solucionado, ahora los campos se limpian antes de traer los nuevos. Cierro el Issue.
