### ISSUE TITLE
Placa con varios espectros, donde se repite el objeto 

### ISSUE THREAD

**Issue by matiannu** [midusi/spectrogram#93]
Necesitamos que el programa reconozca durante la carga de datos si hay dos o mas espectros de un mismo objeto, y que al exportarlos lo haga con archivos con diferentes nombres. (porque sino me los sobreescribe)

**Comment by Sansanto2000** [comment]
Se charlo este tema en la ultima reunion. Dejo constancia de la solucion definida para enfrentarlo:
- Se va a utilizar la estrategia de nombramiento: {nombrePlaca}_{MainID}_{sufijo}
- ‘sufijo’ sería un valor opcional.
- La exportación falla si se detecta que hay 2 archivos idénticos -> Se le advierte al usuario -> El usuario modifica algún sufijos -> Reintentar la exportación.

**Comment by Sansanto2000** [comment]
Issue solucionado, tambien se resolvio el borrado de los archivos con nombres viejos de una placa al momento de generar los archivos nuevos que se exportan de la misma.
En breve se mergean los cambios a dev.

**Comment by Sansanto2000** [comment]
Reabro Issue, estaba usando OBJECT para el renombre del formato, eso es un error, ahora hay que usar MainID

**Comment by Sansanto2000** [comment]
Reabro Issue para solucionar bugs menores en relacion al agregado del campo SUFFIX, el cual se buguea al realizar la busqueda de metadatos

**Comment by Sansanto2000** [comment]
> Reabro Issue para solucionar bugs menores en relacion al agregado del campo SUFFIX, el cual se buguea al realizar la busqueda de metadatos

Solucionado, mergeo cambios a dev.

**Comment by Sansanto2000** [comment]
> Se charlo este tema en la ultima reunion. Dejo constancia de la solucion definida para enfrentarlo:
> 
> * Se va a utilizar la estrategia de nombramiento: {nombrePlaca}_{MainID}_{sufijo}
> * ‘sufijo’ sería un valor opcional.
> * La exportación falla si se detecta que hay 2 archivos idénticos -> Se le advierte al usuario -> El usuario modifica algún sufijos -> Reintentar la exportación.

Me equivoque y use OBJECT en vez de MainID para el nuevo esquema de nombramiento, aun asi MainID es un campo problematico para usar durante el nombramiento debido a sus potenciales espacios a mitad del nombre y problemas relacionados al flujo de uso de la app, ya que es posible exportar los FITS sin haber definido el MainID. No obstante ya tengo todo bien implementado y funcional con el esquema de nombramiento '{nombrePlaca}_{OBJECT}_{sufijo}', por lo que voy a consultar si este esquema de nombramiento sirve antes de decidir si hacer mas cambios o no.

**Comment by Sansanto2000** [comment]
Corregido esquema de nombramiento a  {FILENAME}\_{MAIN-ID}\_{SUFIXX} en los ultimos comits. 
Cierro Issue, en breve mergeo los cambios a development
